### ISSUE TITLE
项目中的composer.json依赖不完整吧 

### ISSUE THREAD

**Issue by wujunze** [beyoio/beyod#1]
![image](https://user-images.githubusercontent.com/12997869/50500370-d4e4b100-0a8b-11e9-91a0-a5f170ad56ff.png)

看你的代码中用了Yii框架很多Class    但是composer.json没有依赖

**Comment by zhangxugg** [comment]
beyod-app是项目模板，
beyod是框架核心库，实际使用时，使用beyod-app项目，加载必要的依赖就行。

**Comment by wujunze** [comment]
好吧
